version: "3.7"

services:
  imageify:
  build:
      context: .
      dockerfile: Dockerfile
    restart: always    
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 7769:3000
    user: root
    volumes:
      - ./storage:/app/storage

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: imageify
      MONGO_INITDB_ROOT_PASSWORD: changethis
    ports:
      - 27017:27017
    user: root
    volumes:
      - ./mongodb:/data/db
